# Generated by Django 3.0.1 on 2020-02-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200207_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dsec',
            field=models.CharField(max_length=200),
        ),
    ]
